<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Homework 3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="fullcontent">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Homework 3</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="task-1-conceptual-questions" class="level2">
<h2 class="anchored" data-anchor-id="task-1-conceptual-questions">Task 1: Conceptual Questions</h2>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section">1.</h3>
<blockquote class="blockquote">
<p>The relative path used to access a file in the myFolder folder would be read_csv(“../MyData.csv”)</p>
</blockquote>
</section>
<section id="section-1" class="level3">
<h3 class="anchored" data-anchor-id="section-1">2.</h3>
<blockquote class="blockquote">
<p>R Projects house several files that can all be used together to create an output object. Having access to all of those files in one place makes it easy to make edits in each file that effect the output.</p>
</blockquote>
</section>
<section id="section-2" class="level3">
<h3 class="anchored" data-anchor-id="section-2">3.</h3>
<blockquote class="blockquote">
<p>Git is a version control software that allows for the “snap-shotting” of programming files to ensure that older versions of a file can be recovered and altered. Github is software that houses repositories of Git files. Changes to files using Git can be committed and pushed to a Github repository, and files on Github can be pulled from the software for local editing.</p>
</blockquote>
</section>
<section id="section-3" class="level3">
<h3 class="anchored" data-anchor-id="section-3">4.</h3>
<blockquote class="blockquote">
<p>Tibbles print data in different ways than dataframes, displaying the type of data that is shown in each column (integer, character, etc.). Also tibbles do not coerce down to a vector when we subset one column with [], where a dataframe would.</p>
</blockquote>
</section>
<section id="section-4" class="level3">
<h3 class="anchored" data-anchor-id="section-4">5.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'purrr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dplyr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'stringr' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lubridate' was built under R version 4.3.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>iris <span class="sc">|&gt;</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">starts_with</span>(<span class="st">"Petal"</span>), Species) <span class="sc">|&gt;</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Petal.Length <span class="sc">&lt;</span> <span class="fl">1.55</span>) <span class="sc">|&gt;</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(Species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 37 × 3
   Petal.Length Petal.Width Species
          &lt;dbl&gt;       &lt;dbl&gt; &lt;fct&gt;  
 1          1.4         0.2 setosa 
 2          1.4         0.2 setosa 
 3          1.3         0.2 setosa 
 4          1.5         0.2 setosa 
 5          1.4         0.2 setosa 
 6          1.4         0.3 setosa 
 7          1.5         0.2 setosa 
 8          1.4         0.2 setosa 
 9          1.5         0.1 setosa 
10          1.5         0.2 setosa 
# ℹ 27 more rows</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The two sets of code produce the same 37 x 3 tibble from the iris dataset.</p>
</blockquote>
</section>
<section id="section-5" class="level3">
<h3 class="anchored" data-anchor-id="section-5">6.</h3>
<blockquote class="blockquote">
<p>Long format data means that the data is formatted so there are more rows than columns when possible. This usually means there is one observation in a given row, and this format is generally preferred for statistical analysis. Wide format data on the other hand will often contain multiple observations in a single row.</p>
</blockquote>
</section>
</section>
<section id="task-2-reading-delimited-data" class="level2">
<h2 class="anchored" data-anchor-id="task-2-reading-delimited-data">Task 2: Reading Delimited Data</h2>
</section>
<section id="glass-data" class="level2">
<h2 class="anchored" data-anchor-id="glass-data">Glass data</h2>
<section id="section-6" class="level3">
<h3 class="anchored" data-anchor-id="section-6">1.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>glass <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://www4.stat.ncsu.edu/~online/datasets/glass.data"</span>, </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">col_names =</span> <span class="fu">c</span>(<span class="st">"Id"</span>, <span class="st">"RI"</span>, <span class="st">"Na"</span>, <span class="st">"Mg"</span>, <span class="st">"Al"</span>, <span class="st">"Si"</span>, <span class="st">"K"</span>, <span class="st">"Ca"</span>, <span class="st">"Ba"</span>, <span class="st">"Fe"</span>,<span class="st">"Type_of_Glass"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 214 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (11): Id, RI, Na, Mg, Al, Si, K, Ca, Ba, Fe, Type_of_Glass

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>glass</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 214 × 11
      Id    RI    Na    Mg    Al    Si     K    Ca    Ba    Fe Type_of_Glass
   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;         &lt;dbl&gt;
 1     1  1.52  13.6  4.49  1.1   71.8  0.06  8.75     0  0                1
 2     2  1.52  13.9  3.6   1.36  72.7  0.48  7.83     0  0                1
 3     3  1.52  13.5  3.55  1.54  73.0  0.39  7.78     0  0                1
 4     4  1.52  13.2  3.69  1.29  72.6  0.57  8.22     0  0                1
 5     5  1.52  13.3  3.62  1.24  73.1  0.55  8.07     0  0                1
 6     6  1.52  12.8  3.61  1.62  73.0  0.64  8.07     0  0.26             1
 7     7  1.52  13.3  3.6   1.14  73.1  0.58  8.17     0  0                1
 8     8  1.52  13.2  3.61  1.05  73.2  0.57  8.24     0  0                1
 9     9  1.52  14.0  3.58  1.37  72.1  0.56  8.3      0  0                1
10    10  1.52  13    3.6   1.36  73.0  0.57  8.4      0  0.11             1
# ℹ 204 more rows</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Data was successfully read in and converted to a tibble containing 214 rows.</p>
</blockquote>
</section>
<section id="section-7" class="level3">
<h3 class="anchored" data-anchor-id="section-7">2.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>glass <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Type_of_Glass =</span> <span class="fu">factor</span>(Type_of_Glass,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">7</span>),</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>                                <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"building_windows_float_processed"</span>,<span class="st">"building_windows_non_float_processed"</span>,<span class="st">"vehicle_windows_float_processed"</span>,<span class="st">"vehicle_windows_non_float_processed"</span>,<span class="st">"containers"</span>,<span class="st">"tableware"</span>,<span class="st">"headlamps"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 214 × 11
      Id    RI    Na    Mg    Al    Si     K    Ca    Ba    Fe Type_of_Glass    
   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;fct&gt;            
 1     1  1.52  13.6  4.49  1.1   71.8  0.06  8.75     0  0    building_windows…
 2     2  1.52  13.9  3.6   1.36  72.7  0.48  7.83     0  0    building_windows…
 3     3  1.52  13.5  3.55  1.54  73.0  0.39  7.78     0  0    building_windows…
 4     4  1.52  13.2  3.69  1.29  72.6  0.57  8.22     0  0    building_windows…
 5     5  1.52  13.3  3.62  1.24  73.1  0.55  8.07     0  0    building_windows…
 6     6  1.52  12.8  3.61  1.62  73.0  0.64  8.07     0  0.26 building_windows…
 7     7  1.52  13.3  3.6   1.14  73.1  0.58  8.17     0  0    building_windows…
 8     8  1.52  13.2  3.61  1.05  73.2  0.57  8.24     0  0    building_windows…
 9     9  1.52  14.0  3.58  1.37  72.1  0.56  8.3      0  0    building_windows…
10    10  1.52  13    3.6   1.36  73.0  0.57  8.4      0  0.11 building_windows…
# ℹ 204 more rows</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Used the factor function to convert the levels of Type_of_Glass from numeric values 1-7 to character strings. The tibble still contains 214 rows</p>
</blockquote>
</section>
<section id="section-8" class="level3">
<h3 class="anchored" data-anchor-id="section-8">3.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>glass <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Type_of_Glass =</span> <span class="fu">factor</span>(Type_of_Glass,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">7</span>),</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>                                <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"building_windows_float_processed"</span>,<span class="st">"building_windows_non_float_processed"</span>,<span class="st">"vehicle_windows_float_processed"</span>,<span class="st">"vehicle_windows_non_float_processed"</span>,<span class="st">"containers"</span>,<span class="st">"tableware"</span>,<span class="st">"headlamps"</span>))) <span class="sc">|&gt;</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>((Fe <span class="sc">&lt;</span> <span class="fl">0.2</span>) <span class="sc">&amp;</span> (Type_of_Glass <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"tableware"</span>,<span class="st">"headlamps"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 38 × 11
      Id    RI    Na    Mg    Al    Si     K    Ca    Ba    Fe Type_of_Glass
   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;fct&gt;        
 1   177  1.52  14    2.39  1.56  72.4  0     9.57  0        0 tableware    
 2   178  1.52  13.8  2.41  1.19  72.8  0     9.77  0        0 tableware    
 3   179  1.52  14.5  2.24  1.62  72.4  0     9.26  0        0 tableware    
 4   180  1.52  14.1  2.19  1.66  72.7  0     9.32  0        0 tableware    
 5   181  1.51  14.4  1.74  1.54  74.6  0     7.59  0        0 tableware    
 6   182  1.52  15.0  0.78  1.74  72.5  0     9.95  0        0 tableware    
 7   183  1.52  14.2  0     2.09  72.7  0    10.9   0        0 tableware    
 8   184  1.52  14.6  0     0.56  73.5  0    11.2   0        0 tableware    
 9   185  1.51  17.4  0     0.34  75.4  0     6.65  0        0 tableware    
10   186  1.51  13.7  3.2   1.81  72.8  1.76  5.43  1.19     0 headlamps    
# ℹ 28 more rows</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Continued the chain to keep only records with Fe values less than 0.2 and only tableware and headlamp glass types. After filtering the records, there are only 38 rows printed.</p>
</blockquote>
</section>
</section>
<section id="yeast-data" class="level2">
<h2 class="anchored" data-anchor-id="yeast-data">Yeast data</h2>
<section id="section-9" class="level3">
<h3 class="anchored" data-anchor-id="section-9">1.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>yeast <span class="ot">&lt;-</span> <span class="fu">read_table</span>(<span class="st">"https://www4.stat.ncsu.edu/~online/datasets/yeast.data"</span>, </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">col_names =</span> <span class="fu">c</span>(<span class="st">"seq_name"</span>,<span class="st">"mcg"</span>,<span class="st">"gvh"</span>,<span class="st">"alm"</span>,<span class="st">"mit"</span>,<span class="st">"erl"</span>,<span class="st">"pox"</span>,<span class="st">"vac"</span>,<span class="st">"nuc"</span>,<span class="st">"class"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
── Column specification ────────────────────────────────────────────────────────
cols(
  seq_name = col_character(),
  mcg = col_double(),
  gvh = col_double(),
  alm = col_double(),
  mit = col_double(),
  erl = col_double(),
  pox = col_double(),
  vac = col_double(),
  nuc = col_double(),
  class = col_character()
)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>yeast</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,484 × 10
   seq_name     mcg   gvh   alm   mit   erl   pox   vac   nuc class
   &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;
 1 ADT1_YEAST  0.58  0.61  0.47  0.13   0.5   0    0.48  0.22 MIT  
 2 ADT2_YEAST  0.43  0.67  0.48  0.27   0.5   0    0.53  0.22 MIT  
 3 ADT3_YEAST  0.64  0.62  0.49  0.15   0.5   0    0.53  0.22 MIT  
 4 AAR2_YEAST  0.58  0.44  0.57  0.13   0.5   0    0.54  0.22 NUC  
 5 AATM_YEAST  0.42  0.44  0.48  0.54   0.5   0    0.48  0.22 MIT  
 6 AATC_YEAST  0.51  0.4   0.56  0.17   0.5   0.5  0.49  0.22 CYT  
 7 ABC1_YEAST  0.5   0.54  0.48  0.65   0.5   0    0.53  0.22 MIT  
 8 BAF1_YEAST  0.48  0.45  0.59  0.2    0.5   0    0.58  0.34 NUC  
 9 ABF2_YEAST  0.55  0.5   0.66  0.36   0.5   0    0.49  0.22 MIT  
10 ABP1_YEAST  0.4   0.39  0.6   0.15   0.5   0    0.58  0.3  CYT  
# ℹ 1,474 more rows</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The data is space delimited (2 spaces), so the read_table() function was used.</p>
</blockquote>
</section>
<section id="section-10" class="level3">
<h3 class="anchored" data-anchor-id="section-10">2.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>yeast <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>seq_name,<span class="sc">-</span>nuc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,484 × 8
     mcg   gvh   alm   mit   erl   pox   vac class
   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;
 1  0.58  0.61  0.47  0.13   0.5   0    0.48 MIT  
 2  0.43  0.67  0.48  0.27   0.5   0    0.53 MIT  
 3  0.64  0.62  0.49  0.15   0.5   0    0.53 MIT  
 4  0.58  0.44  0.57  0.13   0.5   0    0.54 NUC  
 5  0.42  0.44  0.48  0.54   0.5   0    0.48 MIT  
 6  0.51  0.4   0.56  0.17   0.5   0.5  0.49 CYT  
 7  0.5   0.54  0.48  0.65   0.5   0    0.53 MIT  
 8  0.48  0.45  0.59  0.2    0.5   0    0.58 NUC  
 9  0.55  0.5   0.66  0.36   0.5   0    0.49 MIT  
10  0.4   0.39  0.6   0.15   0.5   0    0.58 CYT  
# ℹ 1,474 more rows</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>De-selecting the 2 columns was done with the - operator rather than explicitly selecting the other 8 columns.</p>
</blockquote>
</section>
<section id="section-11" class="level3">
<h3 class="anchored" data-anchor-id="section-11">3.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>yeast <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>seq_name,<span class="sc">-</span>nuc) <span class="sc">|&gt;</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="at">.fns =</span> <span class="fu">list</span>(<span class="at">mean =</span> mean, <span class="at">median =</span> median), <span class="at">.names =</span> <span class="st">"{.fn}_{.col}"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,484 × 22
     mcg   gvh   alm   mit   erl   pox   vac class mean_mcg median_mcg mean_gvh
   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;
 1  0.58  0.61  0.47  0.13   0.5   0    0.48 MIT      0.500       0.49    0.500
 2  0.43  0.67  0.48  0.27   0.5   0    0.53 MIT      0.500       0.49    0.500
 3  0.64  0.62  0.49  0.15   0.5   0    0.53 MIT      0.500       0.49    0.500
 4  0.58  0.44  0.57  0.13   0.5   0    0.54 NUC      0.500       0.49    0.500
 5  0.42  0.44  0.48  0.54   0.5   0    0.48 MIT      0.500       0.49    0.500
 6  0.51  0.4   0.56  0.17   0.5   0.5  0.49 CYT      0.500       0.49    0.500
 7  0.5   0.54  0.48  0.65   0.5   0    0.53 MIT      0.500       0.49    0.500
 8  0.48  0.45  0.59  0.2    0.5   0    0.58 NUC      0.500       0.49    0.500
 9  0.55  0.5   0.66  0.36   0.5   0    0.49 MIT      0.500       0.49    0.500
10  0.4   0.39  0.6   0.15   0.5   0    0.58 CYT      0.500       0.49    0.500
# ℹ 1,474 more rows
# ℹ 11 more variables: median_gvh &lt;dbl&gt;, mean_alm &lt;dbl&gt;, median_alm &lt;dbl&gt;,
#   mean_mit &lt;dbl&gt;, median_mit &lt;dbl&gt;, mean_erl &lt;dbl&gt;, median_erl &lt;dbl&gt;,
#   mean_pox &lt;dbl&gt;, median_pox &lt;dbl&gt;, mean_vac &lt;dbl&gt;, median_vac &lt;dbl&gt;</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The across function was used to access all of the numeric columns and create new columns where a function (mean or median) was applied.</p>
</blockquote>
</section>
</section>
<section id="task-3-combining-excel-and-delimited-data" class="level2">
<h2 class="anchored" data-anchor-id="task-3-combining-excel-and-delimited-data">Task 3: Combining Excel and Delimited Data</h2>
<section id="section-12" class="level3">
<h3 class="anchored" data-anchor-id="section-12">1.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>wines <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"../white-wine.xlsx"</span>, <span class="at">sheet =</span> <span class="dv">1</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>wines</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4,898 × 12
   `fixed acidity` `volatile acidity` `citric acid` `residual sugar` chlorides
             &lt;dbl&gt;              &lt;dbl&gt;         &lt;dbl&gt;            &lt;dbl&gt;     &lt;dbl&gt;
 1               7               0.27          0.36             20.7     0.045
 2              63               0.3           0.34              1.6     0.049
 3              81               0.28          0.4               6.9     0.05 
 4              72               0.23          0.32              8.5     0.058
 5              72               0.23          0.32              8.5     0.058
 6              81               0.28          0.4               6.9     0.05 
 7              62               0.32          0.16              7       0.045
 8               7               0.27          0.36             20.7     0.045
 9              63               0.3           0.34              1.6     0.049
10              81               0.22          0.43              1.5     0.044
# ℹ 4,888 more rows
# ℹ 7 more variables: `free sulfur dioxide` &lt;dbl&gt;,
#   `total sulfur dioxide` &lt;dbl&gt;, density &lt;dbl&gt;, pH &lt;dbl&gt;, sulphates &lt;dbl&gt;,
#   alcohol &lt;dbl&gt;, quality &lt;dbl&gt;</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The Excel dataset was placed in the folder one above the Quarto document’s working directory, so a relative path was used to read the data in.</p>
</blockquote>
</section>
<section id="section-13" class="level3">
<h3 class="anchored" data-anchor-id="section-13">2.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>names_wine <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"../white-wine.xlsx"</span>, <span class="at">sheet =</span> <span class="dv">2</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>names_wine</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 1
   Variables           
   &lt;chr&gt;               
 1 fixed_acidity       
 2 volatile_acidity    
 3 citric_acid         
 4 residual_sugar      
 5 chlorides           
 6 free_sulfur_dioxide 
 7 total_sulfur_dioxide
 8 density             
 9 pH                  
10 sulphates           
11 alcohol             
12 quality             </code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(wines) <span class="ot">&lt;-</span> names_wine<span class="sc">$</span>Variables</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>wines</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4,898 × 12
   fixed_acidity volatile_acidity citric_acid residual_sugar chlorides
           &lt;dbl&gt;            &lt;dbl&gt;       &lt;dbl&gt;          &lt;dbl&gt;     &lt;dbl&gt;
 1             7             0.27        0.36           20.7     0.045
 2            63             0.3         0.34            1.6     0.049
 3            81             0.28        0.4             6.9     0.05 
 4            72             0.23        0.32            8.5     0.058
 5            72             0.23        0.32            8.5     0.058
 6            81             0.28        0.4             6.9     0.05 
 7            62             0.32        0.16            7       0.045
 8             7             0.27        0.36           20.7     0.045
 9            63             0.3         0.34            1.6     0.049
10            81             0.22        0.43            1.5     0.044
# ℹ 4,888 more rows
# ℹ 7 more variables: free_sulfur_dioxide &lt;dbl&gt;, total_sulfur_dioxide &lt;dbl&gt;,
#   density &lt;dbl&gt;, pH &lt;dbl&gt;, sulphates &lt;dbl&gt;, alcohol &lt;dbl&gt;, quality &lt;dbl&gt;</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The names_wine object was read in as a tibble, but needed to be a vector to be assigned to the colnames of the wines tibble. This was done by accessing the first column of the tibble (a vector).</p>
</blockquote>
</section>
<section id="section-14" class="level3">
<h3 class="anchored" data-anchor-id="section-14">3.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>wines <span class="ot">&lt;-</span> wines <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">type =</span> <span class="st">"white"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>In order for the type column to be added, I needed to overwrite the original tibble (was not working without the overwrite).</p>
</blockquote>
</section>
<section id="section-15" class="level3">
<h3 class="anchored" data-anchor-id="section-15">4.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>reds <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">"../red-wine.csv"</span>, <span class="at">delim =</span> <span class="st">";"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 1599 Columns: 12
── Column specification ────────────────────────────────────────────────────────
Delimiter: ";"
dbl (12): fixed acidity, volatile acidity, citric acid, residual sugar, chlo...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(reds) <span class="ot">=</span> names_wine<span class="sc">$</span>Variables</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>reds <span class="ot">&lt;-</span> reds <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">type =</span> <span class="st">"red"</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>reds</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,599 × 13
   fixed_acidity volatile_acidity citric_acid residual_sugar chlorides
           &lt;dbl&gt;            &lt;dbl&gt;       &lt;dbl&gt;          &lt;dbl&gt;     &lt;dbl&gt;
 1           7.4             0.7         0               1.9     0.076
 2           7.8             0.88        0               2.6     0.098
 3           7.8             0.76        0.04            2.3     0.092
 4          11.2             0.28        0.56            1.9     0.075
 5           7.4             0.7         0               1.9     0.076
 6           7.4             0.66        0               1.8     0.075
 7           7.9             0.6         0.06            1.6     0.069
 8           7.3             0.65        0               1.2     0.065
 9           7.8             0.58        0.02            2       0.073
10           7.5             0.5         0.36            6.1     0.071
# ℹ 1,589 more rows
# ℹ 8 more variables: free_sulfur_dioxide &lt;dbl&gt;, total_sulfur_dioxide &lt;dbl&gt;,
#   density &lt;dbl&gt;, pH &lt;dbl&gt;, sulphates &lt;dbl&gt;, alcohol &lt;dbl&gt;, quality &lt;dbl&gt;,
#   type &lt;chr&gt;</code></pre>
</div>
</div>
</section>
<section id="section-16" class="level3">
<h3 class="anchored" data-anchor-id="section-16">5.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>all_wines <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">bind_rows</span>(wines,reds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>There were 4,898 rows in the white wine dataset and 1,599 rows in the red wine dataset. When these datasets are concatenated, they should have 6,497 rows. This is confirmed with the all_wines tibble.</p>
</blockquote>
</section>
<section id="section-17" class="level3">
<h3 class="anchored" data-anchor-id="section-17">6.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>all_wines <span class="sc">|&gt;</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>((quality <span class="sc">&gt;</span> <span class="fl">6.5</span>) <span class="sc">&amp;</span> (alcohol <span class="sc">&lt;</span> <span class="dv">132</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,206 × 13
   fixed_acidity volatile_acidity citric_acid residual_sugar chlorides
           &lt;dbl&gt;            &lt;dbl&gt;       &lt;dbl&gt;          &lt;dbl&gt;     &lt;dbl&gt;
 1            66             0.16        0.4             1.5     0.044
 2            66             0.17        0.38            1.5     0.032
 3            62             0.66        0.48            1.2     0.029
 4            62             0.66        0.48            1.2     0.029
 5            64             0.31        0.38            2.9     0.038
 6            68             0.26        0.42            1.7     0.049
 7            72             0.32        0.36            2       0.033
 8            74             0.18        0.31            1.4     0.058
 9            66             0.25        0.29            1.1     0.068
10            62             0.16        0.33            1.1     0.057
# ℹ 1,196 more rows
# ℹ 8 more variables: free_sulfur_dioxide &lt;dbl&gt;, total_sulfur_dioxide &lt;dbl&gt;,
#   density &lt;dbl&gt;, pH &lt;dbl&gt;, sulphates &lt;dbl&gt;, alcohol &lt;dbl&gt;, quality &lt;dbl&gt;,
#   type &lt;chr&gt;</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>After filtering the tibble with these conditions, there are 1,206 rows; down from the original number of 6,497 rows.</p>
</blockquote>
</section>
<section id="section-18" class="level3">
<h3 class="anchored" data-anchor-id="section-18">7.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>all_wines <span class="sc">|&gt;</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>((quality <span class="sc">&gt;</span> <span class="fl">6.5</span>) <span class="sc">&amp;</span> (alcohol <span class="sc">&lt;</span> <span class="dv">132</span>)) <span class="sc">|&gt;</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(quality))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,206 × 13
   fixed_acidity volatile_acidity citric_acid residual_sugar chlorides
           &lt;dbl&gt;            &lt;dbl&gt;       &lt;dbl&gt;          &lt;dbl&gt;     &lt;dbl&gt;
 1            91             0.27        0.45           10.6     0.035
 2            66             0.36        0.29            1.6     0.021
 3            74             0.24        0.36            2       0.031
 4            69             0.36        0.34            4.2     0.018
 5            71             0.26        0.49            2.2     0.032
 6            62             0.66        0.48            1.2     0.029
 7            62             0.66        0.48            1.2     0.029
 8            68             0.26        0.42            1.7     0.049
 9            67             0.23        0.31            2.1     0.046
10            67             0.23        0.31            2.1     0.046
# ℹ 1,196 more rows
# ℹ 8 more variables: free_sulfur_dioxide &lt;dbl&gt;, total_sulfur_dioxide &lt;dbl&gt;,
#   density &lt;dbl&gt;, pH &lt;dbl&gt;, sulphates &lt;dbl&gt;, alcohol &lt;dbl&gt;, quality &lt;dbl&gt;,
#   type &lt;chr&gt;</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The tibble was rearranged by descending quality.</p>
</blockquote>
</section>
<section id="section-19" class="level3">
<h3 class="anchored" data-anchor-id="section-19">8.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>all_wines <span class="sc">|&gt;</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>((quality <span class="sc">&gt;</span> <span class="fl">6.5</span>) <span class="sc">&amp;</span> (alcohol <span class="sc">&lt;</span> <span class="dv">132</span>)) <span class="sc">|&gt;</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(quality)) <span class="sc">|&gt;</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">"acid"</span>), alcohol, type, quality)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,206 × 6
   fixed_acidity volatile_acidity citric_acid alcohol type  quality
           &lt;dbl&gt;            &lt;dbl&gt;       &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt;
 1            91             0.27        0.45     104 white       9
 2            66             0.36        0.29     124 white       9
 3            74             0.24        0.36     125 white       9
 4            69             0.36        0.34     127 white       9
 5            71             0.26        0.49     129 white       9
 6            62             0.66        0.48     128 white       8
 7            62             0.66        0.48     128 white       8
 8            68             0.26        0.42     105 white       8
 9            67             0.23        0.31     107 white       8
10            67             0.23        0.31     107 white       8
# ℹ 1,196 more rows</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The tibble was subsetted to only include the 6 specified columns.</p>
</blockquote>
</section>
<section id="section-20" class="level3">
<h3 class="anchored" data-anchor-id="section-20">9.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>all_wines <span class="sc">|&gt;</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>((quality <span class="sc">&gt;</span> <span class="fl">6.5</span>) <span class="sc">&amp;</span> (alcohol <span class="sc">&lt;</span> <span class="dv">132</span>)) <span class="sc">|&gt;</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(quality)) <span class="sc">|&gt;</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">"acid"</span>), alcohol, type, quality) <span class="sc">|&gt;</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(quality) <span class="sc">|&gt;</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">mean_alc =</span> <span class="fu">mean</span>(alcohol), <span class="at">sd_alc =</span> <span class="fu">sd</span>(alcohol))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,206 × 8
# Groups:   quality [3]
   fixed_acidity volatile_acidity citric_acid alcohol type  quality mean_alc
           &lt;dbl&gt;            &lt;dbl&gt;       &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt;    &lt;dbl&gt;
 1            91             0.27        0.45     104 white       9    122. 
 2            66             0.36        0.29     124 white       9    122. 
 3            74             0.24        0.36     125 white       9    122. 
 4            69             0.36        0.34     127 white       9    122. 
 5            71             0.26        0.49     129 white       9    122. 
 6            62             0.66        0.48     128 white       8     94.1
 7            62             0.66        0.48     128 white       8     94.1
 8            68             0.26        0.42     105 white       8     94.1
 9            67             0.23        0.31     107 white       8     94.1
10            67             0.23        0.31     107 white       8     94.1
# ℹ 1,196 more rows
# ℹ 1 more variable: sd_alc &lt;dbl&gt;</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>2 new columns were created the contain the mean and standard deviation of the alcohol variable for each grouped wine quality value.</p>
</blockquote>
</section>
</section>
<section id="task-4-database-practice" class="level2">
<h2 class="anchored" data-anchor-id="task-4-database-practice">Task 4: Database Practice</h2>
<section id="section-21" class="level3">
<h3 class="anchored" data-anchor-id="section-21">1.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DBI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'DBI' was built under R version 4.3.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>con <span class="ot">&lt;-</span> <span class="fu">dbConnect</span>(RSQLite<span class="sc">::</span><span class="fu">SQLite</span>(),<span class="st">"lahman.db"</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dbListTables</span>(con)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "AllstarFull"         "Appearances"         "AwardsManagers"     
 [4] "AwardsPlayers"       "AwardsShareManagers" "AwardsSharePlayers" 
 [7] "Batting"             "BattingPost"         "CollegePlaying"     
[10] "Fielding"            "FieldingOF"          "FieldingOFsplit"    
[13] "FieldingPost"        "HallOfFame"          "HomeGames"          
[16] "LahmanData"          "Managers"            "ManagersHalf"       
[19] "Parks"               "People"              "Pitching"           
[22] "PitchingPost"        "Salaries"            "Schools"            
[25] "SeriesPost"          "Teams"               "TeamsFranchises"    
[28] "TeamsHalf"           "battingLabels"       "fieldingLabels"     
[31] "pitchingLabels"     </code></pre>
</div>
</div>
</section>
<section id="section-22" class="level3">
<h3 class="anchored" data-anchor-id="section-22">2.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tbl</span>(con,<span class="st">"Teams"</span>) <span class="sc">|&gt;</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(yearID <span class="sc">==</span> <span class="dv">2015</span>) <span class="sc">|&gt;</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 48
   yearID lgID  teamID franchID divID  Rank     G Ghome     W     L DivWin WCWin
    &lt;int&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;    &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;  &lt;chr&gt;
 1   2015 NL    ARI    ARI      W         3   162    81    79    83 N      N    
 2   2015 NL    ATL    ATL      E         4   162    81    67    95 N      N    
 3   2015 AL    BAL    BAL      E         3   162    78    81    81 N      N    
 4   2015 AL    BOS    BOS      E         5   162    81    78    84 N      N    
 5   2015 AL    CHA    CHW      C         4   162    81    76    86 N      N    
 6   2015 NL    CHN    CHC      C         3   162    81    97    65 N      Y    
 7   2015 NL    CIN    CIN      C         5   162    81    64    98 N      N    
 8   2015 AL    CLE    CLE      C         3   161    80    81    80 N      N    
 9   2015 NL    COL    COL      W         5   162    81    68    94 N      N    
10   2015 AL    DET    DET      C         5   161    81    74    87 N      N    
# ℹ 20 more rows
# ℹ 36 more variables: LgWin &lt;chr&gt;, WSWin &lt;chr&gt;, R &lt;int&gt;, AB &lt;int&gt;, H &lt;int&gt;,
#   X2B &lt;int&gt;, X3B &lt;int&gt;, HR &lt;int&gt;, BB &lt;int&gt;, SO &lt;int&gt;, SB &lt;int&gt;, CS &lt;int&gt;,
#   HBP &lt;int&gt;, SF &lt;int&gt;, RA &lt;int&gt;, ER &lt;int&gt;, ERA &lt;dbl&gt;, CG &lt;int&gt;, SHO &lt;int&gt;,
#   SV &lt;int&gt;, IPouts &lt;int&gt;, HA &lt;int&gt;, HRA &lt;int&gt;, BBA &lt;int&gt;, SOA &lt;int&gt;, E &lt;int&gt;,
#   DP &lt;int&gt;, FP &lt;dbl&gt;, name &lt;chr&gt;, park &lt;chr&gt;, attendance &lt;int&gt;, BPF &lt;int&gt;,
#   PPF &lt;int&gt;, teamIDBR &lt;chr&gt;, teamIDlahman45 &lt;chr&gt;, teamIDretro &lt;chr&gt;</code></pre>
</div>
</div>
</section>
<section id="section-23" class="level3">
<h3 class="anchored" data-anchor-id="section-23">3.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tbl</span>(con, <span class="fu">sql</span>(</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"SELECT `Teams` .* </span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="st">   FROM `Teams`</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="st">   WHERE (`yearID` = 2015.0)"</span>)</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 48
   yearID lgID  teamID franchID divID  Rank     G Ghome     W     L DivWin WCWin
    &lt;int&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;    &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;  &lt;chr&gt;
 1   2015 NL    ARI    ARI      W         3   162    81    79    83 N      N    
 2   2015 NL    ATL    ATL      E         4   162    81    67    95 N      N    
 3   2015 AL    BAL    BAL      E         3   162    78    81    81 N      N    
 4   2015 AL    BOS    BOS      E         5   162    81    78    84 N      N    
 5   2015 AL    CHA    CHW      C         4   162    81    76    86 N      N    
 6   2015 NL    CHN    CHC      C         3   162    81    97    65 N      Y    
 7   2015 NL    CIN    CIN      C         5   162    81    64    98 N      N    
 8   2015 AL    CLE    CLE      C         3   161    80    81    80 N      N    
 9   2015 NL    COL    COL      W         5   162    81    68    94 N      N    
10   2015 AL    DET    DET      C         5   161    81    74    87 N      N    
# ℹ 20 more rows
# ℹ 36 more variables: LgWin &lt;chr&gt;, WSWin &lt;chr&gt;, R &lt;int&gt;, AB &lt;int&gt;, H &lt;int&gt;,
#   X2B &lt;int&gt;, X3B &lt;int&gt;, HR &lt;int&gt;, BB &lt;int&gt;, SO &lt;int&gt;, SB &lt;int&gt;, CS &lt;int&gt;,
#   HBP &lt;int&gt;, SF &lt;int&gt;, RA &lt;int&gt;, ER &lt;int&gt;, ERA &lt;dbl&gt;, CG &lt;int&gt;, SHO &lt;int&gt;,
#   SV &lt;int&gt;, IPouts &lt;int&gt;, HA &lt;int&gt;, HRA &lt;int&gt;, BBA &lt;int&gt;, SOA &lt;int&gt;, E &lt;int&gt;,
#   DP &lt;int&gt;, FP &lt;dbl&gt;, name &lt;chr&gt;, park &lt;chr&gt;, attendance &lt;int&gt;, BPF &lt;int&gt;,
#   PPF &lt;int&gt;, teamIDBR &lt;chr&gt;, teamIDlahman45 &lt;chr&gt;, teamIDretro &lt;chr&gt;</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The SQL code was found by applying the show_query() function (from the dplyr package) to the code chain from question #2.</p>
</blockquote>
</section>
<section id="section-24" class="level3">
<h3 class="anchored" data-anchor-id="section-24">4.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tbl</span>(con, <span class="st">"HallOfFame"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(inducted <span class="sc">==</span> <span class="st">"Y"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">ends_with</span>(<span class="st">"ID"</span>), category) <span class="sc">|&gt;</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 340 × 3
   playerID  yearID category         
   &lt;chr&gt;      &lt;int&gt; &lt;chr&gt;            
 1 cobbty01    1936 Player           
 2 ruthba01    1936 Player           
 3 wagneho01   1936 Player           
 4 mathech01   1936 Player           
 5 johnswa01   1936 Player           
 6 lajoina01   1937 Player           
 7 speaktr01   1937 Player           
 8 youngcy01   1937 Player           
 9 bulkemo99   1937 Pioneer/Executive
10 johnsba99   1937 Pioneer/Executive
# ℹ 330 more rows</code></pre>
</div>
</div>
</section>
<section id="section-25" class="level3">
<h3 class="anchored" data-anchor-id="section-25">5.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">inner_join</span>(<span class="fu">tbl</span>(con, <span class="st">"HallOfFame"</span>) <span class="sc">|&gt;</span> <span class="fu">filter</span>(inducted <span class="sc">==</span> <span class="st">"Y"</span>) <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="fu">ends_with</span>(<span class="st">"ID"</span>), category),</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>           <span class="fu">tbl</span>(con, <span class="st">"People"</span>) <span class="sc">|&gt;</span> <span class="fu">select</span>(playerID, nameFirst, nameLast), </span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"playerID"</span> <span class="ot">=</span> <span class="st">"playerID"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 338 × 5
   playerID  yearID category          nameFirst nameLast 
   &lt;chr&gt;      &lt;int&gt; &lt;chr&gt;             &lt;chr&gt;     &lt;chr&gt;    
 1 cobbty01    1936 Player            Ty        Cobb     
 2 ruthba01    1936 Player            Babe      Ruth     
 3 wagneho01   1936 Player            Honus     Wagner   
 4 mathech01   1936 Player            Christy   Mathewson
 5 johnswa01   1936 Player            Walter    Johnson  
 6 lajoina01   1937 Player            Nap       Lajoie   
 7 speaktr01   1937 Player            Tris      Speaker  
 8 youngcy01   1937 Player            Cy        Young    
 9 bulkemo99   1937 Pioneer/Executive Morgan    Bulkeley 
10 johnsba99   1937 Pioneer/Executive Ban       Johnson  
# ℹ 328 more rows</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Combining the tibble of Hall of Fame players with the tibble containing their name information.</p>
</blockquote>
</section>
<section id="section-26" class="level3">
<h3 class="anchored" data-anchor-id="section-26">6.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tbl</span>(con, <span class="st">"Managers"</span>) <span class="sc">|&gt;</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(playerID, G, W, L) <span class="sc">|&gt;</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(playerID) <span class="sc">|&gt;</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">G_managed =</span> <span class="fu">sum</span>(G, <span class="at">na.rm =</span> T),</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">Total_W =</span> <span class="fu">sum</span>(W, <span class="at">na.rm =</span> T),</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">Total_L =</span> <span class="fu">sum</span>(L, <span class="at">na.rm =</span> T)) <span class="sc">|&gt;</span></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect</span>() <span class="sc">|&gt;</span></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Win_pct =</span> Total_W<span class="sc">/</span>G_managed) <span class="sc">|&gt;</span></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Win_pct))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 749 × 5
   playerID  G_managed Total_W Total_L Win_pct
   &lt;chr&gt;         &lt;int&gt;   &lt;int&gt;   &lt;int&gt;   &lt;dbl&gt;
 1 bensove01         1       1       0       1
 2 burwebi01         1       1       0       1
 3 cohenan01         1       1       0       1
 4 ebeldi99          3       3       0       1
 5 falkbi01          1       1       0       1
 6 hardeme01         3       3       0       1
 7 simmote01         1       1       0       1
 8 steinte01         2       2       0       1
 9 sukefcl01         2       2       0       1
10 tamarjo01         1       1       0       1
# ℹ 739 more rows</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Tibble created containing all Managers in descending order by Win percentage.</p>
</blockquote>
</section>
<section id="section-27" class="level3">
<h3 class="anchored" data-anchor-id="section-27">7.</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">inner_join</span>(<span class="fu">inner_join</span>(<span class="fu">tbl</span>(con, <span class="st">"HallOfFame"</span>) <span class="sc">|&gt;</span> <span class="fu">filter</span>(inducted <span class="sc">==</span> <span class="st">"Y"</span>) <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="fu">ends_with</span>(<span class="st">"ID"</span>), category),</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>           <span class="fu">tbl</span>(con, <span class="st">"People"</span>) <span class="sc">|&gt;</span> <span class="fu">select</span>(playerID, nameFirst, nameLast), </span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"playerID"</span> <span class="ot">=</span> <span class="st">"playerID"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>           <span class="fu">collect</span>(),</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tbl</span>(con, <span class="st">"Managers"</span>) <span class="sc">|&gt;</span></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(playerID, G, W, L) <span class="sc">|&gt;</span></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(playerID) <span class="sc">|&gt;</span></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">G_managed =</span> <span class="fu">sum</span>(G, <span class="at">na.rm =</span> T),</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">Total_W =</span> <span class="fu">sum</span>(W, <span class="at">na.rm =</span> T),</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">Total_L =</span> <span class="fu">sum</span>(L, <span class="at">na.rm =</span> T)) <span class="sc">|&gt;</span></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect</span>() <span class="sc">|&gt;</span></span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Win_pct =</span> Total_W<span class="sc">/</span>G_managed) <span class="sc">|&gt;</span></span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Win_pct)),</span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"playerID"</span> <span class="ot">=</span> <span class="st">"playerID"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 97 × 9
   playerID yearID category nameFirst nameLast G_managed Total_W Total_L Win_pct
   &lt;chr&gt;     &lt;int&gt; &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;        &lt;int&gt;   &lt;int&gt;   &lt;int&gt;   &lt;dbl&gt;
 1 cobbty01   1936 Player   Ty        Cobb           933     479     444   0.513
 2 wagneho…   1936 Player   Honus     Wagner           5       1       4   0.2  
 3 mathech…   1936 Player   Christy   Mathews…       346     164     176   0.474
 4 johnswa…   1936 Player   Walter    Johnson        966     529     432   0.548
 5 lajoina…   1937 Player   Nap       Lajoie         700     377     309   0.539
 6 speaktr…   1937 Player   Tris      Speaker       1139     617     520   0.542
 7 youngcy…   1937 Player   Cy        Young            6       3       3   0.5  
 8 mackco01   1937 Manager  Connie    Mack          7755    3731    3948   0.481
 9 mcgrajo…   1937 Manager  John      McGraw        4769    2763    1948   0.579
10 wrighge…   1937 Pioneer… George    Wright          85      59      25   0.694
# ℹ 87 more rows</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The tibbles from the previous 2 questions were combined via an inner join to create the final tibble, consisting of 97 records. This represents 97 people who were both inducted into the Hall of Fame and managed a team.</p>
</blockquote>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>